name: Deploy-Azure-Bicep-1-job

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-bicep-github-actions-29
  WEBAPP_NAME: bicep-029
  LOCATION: westeurope
  TEMPLATE: 01-bicep-webapp/webapp-linux.bicep

permissions:
  contents: read

jobs:
  preview-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az version
            az group create -n "$RESOURCE_GROUP" -l "$LOCATION"

      - name: Preview changes from Bicep (what-if)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group what-if \
              --resource-group "$RESOURCE_GROUP" \
              --template-file "$TEMPLATE" \
              --parameters webAppName="$WEBAPP_NAME"

      - name: Deploy Bicep to Azure
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ${{ env.TEMPLATE }}
          parameters: webAppName=${{ env.WEBAPP_NAME }}
          failOnStdErr: false

      - name: Show deployed app
        run: |
          echo "Name: ${{ steps.deploy.outputs.webAppName }}"
          echo "URL:  ${{ steps.deploy.outputs.webAppUrl }}"
